version: '3.8'

services:
  ckn-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CKN_KAFKA_BROKER=broker:29092
      - CKN_KAFKA_TOPIC=oracle-events
      - CKN_LOG_FILE=ckn_example.log
    volumes:
      - ./:/app  # This mounts the current directory to /app in the container
    networks:
      - ckn-network

networks:
  ckn-network:
    external: True