services:
  ckn-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ckn-daemon
    ports:
      - "5003:5003"
    environment:
      - CKN_KAFKA_BROKER=http://127.0.0.1:9092
